# Cf. Example using yarn
# https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions#example-using-yarn
# Cf. Using CI
# https://help.github.com/en/actions/reference/workflow-commands-for-github-actions

on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    - name: Deploying to GitHub Pages
      run: |
        git config --global user.email "chore@noreply.babydegu.com"
        git config --global user.name "chore"
        echo "machine github.com login chore password $GITHUB_TOKEN" > ~/.netrc
    - name: install Docusaurus and generate file of English strings
      run: cd website && yarn install && yarn run write-translations && cd ..
    - name: crowdin install
      run: |
        sudo apt-get install default-jre
        wget https://artifacts.crowdin.com/repo/deb/crowdin.deb -O crowdin.deb
        sudo dpkg -i crowdin.deb
    - name: translations upload/download
      run: |
        crowdin --config crowdin.yaml upload sources --auto-update -b master
        crowdin --config crowdin.yaml download -b master
      env:
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_API_KEY: ${{ secrets.CROWDIN_API_KEY }}
    - name: build and publish website
      run: cd website && GIT_USER=chore yarn run publish-gh-pages
